# Toasty
Toasty: Speeding Up Network I/O with Cache-Warm Buffers

Toasty consists of two components built on top of the AF_XDP packet I/O framework. First, the userspace packet buffer pool management in AF_XDP works as a LIFO stack rather than a FIFO queue, so that recently recycled warm buffers are reused for future packets immediately. Second is the kernel device driver that populates the NIC RX ring, adjusting the number of buffers in circulation based on incoming load and application processing rate to improve cache locality while remaining resilient to packet loss.

This repo contains the LIFO-based Buffer Pool Userspace component of Toasty. The kernel-space adaptive RX ring refill is present in the Toasty-kernel repo. Workloads used for experimentation are NAT, IDS, Decryption, L2Fwd, MICA, and Maglev.

Here is the simplest command line for running the NAT application:

#+BEGIN_SRC sh
sudo taskset -c <app_core> ./bpf/AF_XDP/xdpsock -i <interface> -A <app_id> -U <umem_size> -s <packet_size> -B -W 
#+END_SRC

Check logs/stats.csv file to get number of packets received and other stats after exiting application.

**The application contains six workloads:**
(App 0)  NAT looks up and rewrites IP address bytes in the packet headers after reading them. 
(App 1) IDS is an application that reads and compares bytes in the payload with a pre-defined pattern. 
(App 2) Decryption is a proxy server in which the application reads the entire payload, decrypts it, and rewrites the contents of the packet. 
(App 3) L2Fwd is a swap-and-forward application which reads and updates the MAC address, and then forwards the packets back into the network. 
(App 4) MICA is an optimized key-value server that handles get/put requests in the packet, retrieves/updates key-value pairs in memory, then sends back the packet to the client. 
(App 5) Maglev is a hashing-based L4 load balancer


**Busy-Poll mode**
In this mode both the application and the driver can be run efficiently on the same core. The kernel driver is explicitly invoked by the application by calling either recvmsg() or sendto(). Invoke this by setting the -B option. The -b option can be used to set the batch size that the driver will use. Note that you have to enable busy_poll explicitly for the netdev. Following setup is included in the setup_script:

#+BEGIN_SRC sh
  echo 2 | sudo tee /sys/class/net/<interface>/napi_defer_hard_irqs
  echo 200000 | sudo tee /sys/class/net/<interface>/gro_flush_timeout
#+END_SRC
